services:
  frontend:
    # image: cqregistry.azurecr.io/samples/web
    build: ./chatbot-web
    ports:
      - 3000:3000
    networks:
      - app

  backend:
    # image: cqregistry.azurecr.io/samples/api
    build: ./chatbot-api
    ports:
      - 5000:5000
    networks:
      - app

  ollama:
    # image: cqregistry.azurecr.io/samples/ollama
    build: ./ollama
    ports:
      - 11434:11434
    networks:
      - app

networks:
  app:
    driver: bridge
